using System.Collections.Generic;
using UnityEngine;

namespace Core.Graphics
{
    [CreateAssetMenu(fileName = "SCO_MaterialRegistry", menuName = "Resources/Core/Material Registry", order = 0)]
    public sealed class RegistryMaterial : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private Material[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedMaterialIDs.cs";

        private readonly Dictionary<string, Material> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => MaterialDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry != null ? entry.name : CoreUtility.STRING_NULL));
        public void AppendEntries(IReadOnlyList<Material> materials) => CoreUtility.AppendEntries(materials, extraEntries, static entry => entry.name, static entry => entry != null);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class MaterialIDs"))
            {
                for (int i = 0; i < MaterialDatabase.GetMaterials(); i++)
                {
                    MaterialID id = MaterialDatabase.GetID(i);

                    generator.Field($"public static readonly MaterialID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
