using UnityEngine;
using Core.Editor;

namespace Core.Graphics
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_MeshRegistry", menuName = "Resources/Core/Mesh Registry", order = 0)]
    public sealed class RegistryMesh : Registry
    {
        [Header("_")]
        [SerializeField, Required] private Mesh[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedMeshIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => MeshDatabase.Build(entries);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class MeshIDs"))
            {
                foreach (SearchEntry<string> entry in MeshDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = MeshDatabase.GetIDIndex(id);

                    generator.Field($"public static readonly MeshID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }
#endif
    }
}
