using UnityEngine;
using Core.Editor;

namespace Core.Graphics
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_IconRegistry", menuName = "Resources/Core/Icon Registry", order = 0)]
    public sealed class RegistryIcon : Registry
    {
        [Header("_")]
        [SerializeField, Required] private Sprite[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedIconIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => IconDatabase.Build(entries);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class IconIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in IconDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = IconDatabase.GetIndex(id);

                    generator.Field($"public static readonly IconID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }
#endif
    }
}
