using System.Collections.Generic;
using UnityEngine;

namespace Core.Graphics
{
    [CreateAssetMenu(fileName = "SCO_MeshRegistry", menuName = "Resources/Core/Mesh Registry", order = 0)]
    public sealed class RegistryMesh : Registry
    {
        [Header("_")]
        [SerializeField, Required] private Mesh[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedMeshIDs.cs";

        private readonly Dictionary<string, Mesh> extraEntries = new();

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => MeshDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry != null ? entry.name : CoreUtility.STRING_NULL));
        public void AppendEntries(IReadOnlyList<Mesh> meshes) => CoreUtility.AppendEntries(meshes, extraEntries, static entry => entry.name, static entry => entry != null);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class MeshIDs"))
            {
                for (int i = 0; i < MeshDatabase.GetMeshes(); i++)
                {
                    MeshID id = MeshDatabase.GetID(i);

                    generator.Field($"public static readonly MeshID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
