using UnityEngine;
using Core.Editor;

namespace Core.Graphics
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_MaterialRegistry", menuName = "Resources/Core/Material Registry", order = 0)]
    public sealed class RegistryMaterial : Registry
    {
        [Header("_")]
        [SerializeField, Required] private Material[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedMaterialIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => MaterialDatabase.Build(entries);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class MaterialIDs"))
            {
                foreach (SearchEntry<string> entry in MaterialDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = MaterialDatabase.GetIDIndex(id);

                    generator.Field($"public static readonly MaterialID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }
#endif
    }
}
