using System.Collections.Generic;
using UnityEngine;

namespace Core.Graphics
{
    [CreateAssetMenu(fileName = "SCO_IconRegistry", menuName = "Resources/Core/Icon Registry", order = 0)]
    public sealed class RegistryIcon : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private Sprite[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedIconIDs.cs";

        private readonly Dictionary<string, Sprite> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => IconDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry != null ? entry.name : CoreUtility.STRING_NULL));
        public void AppendEntries(IReadOnlyList<Sprite> sprites) => CoreUtility.AppendEntries(sprites, extraEntries, static entry => entry.name, static entry => entry != null);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Graphics");
            generator.Line();

            using (generator.Namespace("Core.Graphics"))
            using (generator.Class("public static class IconIDs"))
            {
                for (int i = 0; i < IconDatabase.GetSprites(); i++)
                {
                    IconID id = IconDatabase.GetID(i);

                    generator.Field($"public static readonly IconID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
