using System.Collections.Generic;
using UnityEngine;


namespace Core.Audio
{
    [CreateAssetMenu(fileName = "SCO_SoundRegistry", menuName = "Resources/Core/Sound Registry", order = 0)]
    public sealed class RegistrySound : Registry
    {
        [Header("_")]
        [SerializeField, Required] private AudioClip[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedSoundIDs.cs";

        private readonly Dictionary<string, AudioClip> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => SoundDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry != null ? entry.name : CoreUtility.STRING_NULL));
        public void AppendEntries(IReadOnlyList<AudioClip> clips) => CoreUtility.AppendEntries(clips, extraEntries, static entry => entry.name, static entry => entry != null);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Audio"))
            using (generator.Class("public static class SoundIDs"))
            {
                for (int i = 0; i < SoundDatabase.GetClips(); i++)
                {
                    SoundID id = SoundDatabase.GetID(i);

                    generator.Field($"public static readonly SoundID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
