using UnityEngine;
using Core.Editor;

namespace Core.Audio
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_SoundRegistry", menuName = "Resources/Core/Sound Registry", order = 0)]
    public sealed class RegistrySound : Registry
    {
        [Header("_")]
        [SerializeField, Required] private AudioClip[] entries = null;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedSoundIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => SoundDatabase.Build(entries);

#if UNITY_EDITOR
        [Clickable("Build")]
        internal void Build()
        {
            BuildDatabase();
            Generate();
        }
        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Audio");
            generator.Line();

            using (generator.Namespace("Core.Audio"))
            using (generator.Class("public static class SoundIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in SoundDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;

                    generator.Field($"public static readonly SoundID {id.ToIdentifier()} = new({id.ToLiteral()})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }
#endif
    }
}
