using System;
using System.Collections.Generic;
using System.Text;

namespace Core.Editor
{
    public sealed class SourceGenerator
    {
        private const string INDENT = "    ";

        private readonly StringBuilder builder = new();
        private readonly Stack<string> scopes = new();

        private int indent;

        public SourceGenerator AutoGenerated()
        {
            Line("//------------------------------------------------------------------------------");
            Line("// <auto-generated>");
            Line("//     This file was generated automatically.");
            Line("//     Changes to this file may be overwritten.");
            Line("// </auto-generated>");
            Line("//------------------------------------------------------------------------------");
            Line();

            return this;
        }

        public SourceGenerator Using(string namespaceName)
        {
            return Line($"using {namespaceName};");
        }
        public SourceScope Namespace(string name)
        {
            return Scope($"namespace {name}");
        }
        public SourceScope Class(string declaration)
        {
            return Scope(declaration);
        }
        public SourceScope Struct(string declaration)
        {
            return Scope(declaration);
        }
        public SourceScope Interface(string declaration)
        {
            return Scope(declaration);
        }
        public SourceScope Enum(string declaration)
        {
            return Scope(declaration);
        }
        public SourceScope Method(string declaration)
        {
            return Scope(declaration);
        }
        public SourceScope Scope(string declaration)
        {
            Line(declaration);
            Line("{");

            indent++;
            scopes.Push(declaration);

            return new SourceScope(this);
        }
        internal void EndScope()
        {
            if (indent == 0)
            {
                throw new InvalidOperationException("No scope to close.");
            }

            indent--;
            scopes.Pop();

            Line("}");
        }

        public SourceGenerator Line()
        {
            builder.AppendLine();
            return this;
        }
        public SourceGenerator Line(string text)
        {
            for (int i = 0; i < indent; i++)
            {
                builder.Append(INDENT);
            }

            builder.AppendLine(text);

            return this;
        }
        public SourceGenerator Statement(string statement)
        {
            return Line(statement.EndsWith(";") ? statement : statement + ";");
        }
        public SourceGenerator Field(string declaration)
        {
            return Statement(declaration);
        }
        public SourceGenerator Summary(string text)
        {
            Line("/// <summary>");
            Line($"/// {text}");
            Line("/// </summary>");

            return this;
        }
        public SourceGenerator Attribute(string attribute)
        {
            return Line(attribute.StartsWith("[") ? attribute : $"[{attribute}]");
        }
        public SourceGenerator WriteLines<T>(IEnumerable<T> collection, Func<T, string> selector)
        {
            foreach (var item in collection)
            {
                Line(selector(item));
            }

            return this;
        }
        public override string ToString()
        {
            if (scopes.Count > 0)
            {
                throw new InvalidOperationException($"There are {scopes.Count} unclosed scope(s).");
            }

            return builder.ToString();
        }
        public void Clear()
        {
            builder.Clear();
            scopes.Clear();
            indent = 0;
        }
    }
}