using Core.Editor;
using UnityEditor;
using UnityEngine;

namespace Core.Damage
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_DamageRegistry", menuName = "Resources/Core/Damage Registry", order = 10)]
    public sealed class RegistryDamage : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedDamageTags.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => DamageDatabase.Build(entries);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
        }

        private void GenerateTags()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Damage");
            generator.Line();

            using (generator.Namespace("Core.Damage"))
            using (generator.Class("public static class DamageTags"))
            {
                foreach (SearchEntry<string> entry in DamageDatabase.GetTags().Entries)
                {
                    string id = entry.Value;
                    int index = DamageDatabase.GetTagIndex(id);

                    generator.Field($"public static readonly DamageTag {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        /// <summary> Overrides entries </summary>
        public void OverrideEntries(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
