using System;
using System.Collections.Generic;
using UnityEngine;

namespace Core.Damage
{
    [CreateAssetMenu(fileName = "SCO_DamageRegistry", menuName = "Resources/Core/Damage Registry", order = 10)]
    public sealed class RegistryDamage : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField, Required] private string tagPath = "Assets/Scripts/SCR_GeneratedDamageTags.cs";

        private readonly HashSet<string> extraTags = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => DamageDatabase.Build(CoreUtility.MergeEntries(tags, extraTags));
        public void AppendTags(IReadOnlyList<string> tags) => CoreUtility.AppendUnique(tags, extraTags, StringComparer.Ordinal);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
        }

        private void GenerateTags()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Damage"))
            using (generator.Class("public static class DamageTags"))
            {
                foreach (DamageTag tag in DamageDatabase.GetTags())
                {
                    string key = tag.Key;
                    int index = tag.Index;

                    generator.Field($"public static readonly DamageTag {key.ToIdentifier()} = new({key.ToLiteral()},{index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(tagPath, generator.ToString());
        }
#endif
    }
}
