using System.Collections.Generic;
using UnityEngine;

namespace Core.Faction
{
    [CreateAssetMenu(fileName = "SCO_FactionRegistry", menuName = "Resources/Game/Faction Registry", order = -10)]
    public sealed class RegistryFaction : Registry
    {
        public override int Priority => 0;

        [Header("_")]
        [SerializeField] private FactionEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedFactionIDs.cs";

        private readonly Dictionary<string, FactionEntry> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => FactionDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key));
        public void AppendEntries(IReadOnlyList<FactionEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);


#if UNITY_EDITOR
        protected override void OnValidate()
        {
            base.OnValidate();

            for (int i = 0; i < entries.Length; i++)
            {
                entries[i].OnValidate();
            }
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Core.Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Faction"))
            using (generator.Class("public static class FactionIDs"))
            {
                foreach (FactionDefinition definition in FactionDatabase.GetDefinitions())
                {
                    FactionID id = definition.ID;

                    generator.Field($"public static readonly FactionID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Core.Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
