using System;
using System.Collections.Generic;
using UnityEngine;

namespace Core.Item
{
    [CreateAssetMenu(fileName = "SCO_ItemRegistry", menuName = "Resources/Core/Item Registry", order = 10)]
    public sealed class RegistryItem : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField] private ItemEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedItemIDs.cs";
        [SerializeField, Required] private string tagsPath = "Assets/Scripts/SCR_GeneratedItemTags.cs";

        private readonly Dictionary<string, ItemEntry> extraEntries = new();
        private readonly HashSet<string> extraTags = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => ItemDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key), CoreUtility.MergeEntries(tags, extraTags));
        public void AppendEntries(IReadOnlyList<ItemEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);
        public void AppendTags(IReadOnlyList<string> tags) => CoreUtility.AppendUnique(tags, extraTags, StringComparer.Ordinal);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
            GenerateIDs();
        }

        private void GenerateTags()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Item");
            generator.Line();

            using (generator.Namespace("Core.Item"))
            using (generator.Class("public static class ItemTags"))
            {
                foreach (ItemTag tag in ItemDatabase.GetTags())
                {
                    generator.Field($"public static readonly ItemTag {tag.Key.ToIdentifier()} = new({tag.Key.ToLiteral()},{tag.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(tagsPath, generator.ToString());
        }
        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Item");
            generator.Line();

            using (generator.Namespace("Core.Item"))
            using (generator.Class("public static class ItemIDs"))
            {
                foreach (ItemDefinition definition in ItemDatabase.GetDefinitions())
                {
                    ItemID id = definition.ID;

                    generator.Field($"public static readonly ItemID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
