using Core.Editor;
using UnityEditor;
using UnityEngine;

namespace Core.Item
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_ItemRegistry", menuName = "Resources/Core/Item Registry", order = 10)]
    public sealed class RegistryItem : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField] private ItemEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idsPath = "Assets/Scripts/SCR_GeneratedItemIDs.cs";
        [SerializeField, Required] private string tagPath = "Assets/Scripts/SCR_GeneratedItemTags.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => ItemDatabase.Build(ids, tags, entries);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
            GenerateIDs();
        }

        private void GenerateTags()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Item");
            generator.Line();

            using (generator.Namespace("Core.Item"))
            using (generator.Class("public static class ItemTags"))
            {
                foreach (SearchEntry<string> entry in ItemDatabase.GetTags().Entries)
                {
                    string id = entry.Value;
                    int index = ItemDatabase.GetTagIndex(id);

                    generator.Field($"public static readonly ItemTag {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(tagPath, generator.ToString());
        }
        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Item");
            generator.Line();

            using (generator.Namespace("Core.Item"))
            using (generator.Class("public static class ItemIDs"))
            {
                foreach (SearchEntry<string> entry in ItemDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = ItemDatabase.GetIDIndex(id);

                    generator.Field($"public static readonly ItemID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(idsPath, generator.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides tags </summary>
        public void OverrideTags(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            tags = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                tags[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides entries </summary>
        public void OverrideEntries(ItemEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new ItemEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
