using Core.Editor;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Core.Trait
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_TraitRegistry", menuName = "Resources/Core/Trait Registry", order = 10)]
    public sealed class RegistryTrait : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;

        [Header("_")]
        [SerializeField] private TraitEntry[] entries;

        [Header("_")]
        [Info("You can use 'dreampuf.github.io' for graph view")]
        [SerializeField, Required] private string idsPath = "Assets/Scripts/SCR_GeneratedTraitIDs.cs";
        [SerializeField, Required] private string graphPath = "Assets/Data/SCO_GeneratedTraitGraph.dot";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => TraitDatabase.Build(ids, entries);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
            GenerateGraph();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Trait");
            generator.Line();

            using (generator.Namespace("Core.Trait"))
            using (generator.Class("public static class TraitIDs"))
            {
                foreach (SearchEntry<string> entry in TraitDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;    
                    generator.Field($"public static readonly TraitID {id.ToIdentifier()} = new({id.ToLiteral()})");
                }
            }

            GenerateTextFile(idsPath, generator.ToString());
        }
        private void GenerateGraph()
        {
            StringBuilder sb = new();
            sb.AppendLine("digraph Traits");
            sb.AppendLine("{");
            {
                foreach (TraitDefinition definition in TraitDatabase.GetDatabase()) // senin veri kaynaðýn neyse
                {
                    bool hasIncompatibles = definition.IncompatibleIDs.Length > 0;

                    if (hasIncompatibles)
                    {
                        foreach (TraitID incompatibleID in definition.IncompatibleIDs)
                        {
                            if (incompatibleID.IsValid)
                            {
                                sb.AppendLine($"  \"{definition.ID.Key}\" -> \"{incompatibleID.Key}\";");
                            }
                        }
                    }
                    else
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\";");
                    }
                }
            }
            sb.AppendLine("}");

            GenerateTextFile(graphPath, sb.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides entries </summary>
        public void OverrideEntries(TraitEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new TraitEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }


            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
