using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Core.Trait
{
    [CreateAssetMenu(fileName = "SCO_TraitRegistry", menuName = "Resources/Core/Trait Registry", order = 10)]
    public sealed class RegistryTrait : Registry
    {
        [Header("_")]
        [SerializeField] private TraitEntry[] entries;

        [Header("_")]
        [Info("You can use 'dreampuf.github.io' for graph view")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedTraitIDs.cs";
        [SerializeField, Required] private string graphPath = "Assets/Data/SCO_GeneratedTraitGraph.dot";

        private readonly Dictionary<string, TraitEntry> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => TraitDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key));
        public void AppendEntries(IReadOnlyList<TraitEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
            GenerateGraph();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Trait");
            generator.Line();

            using (generator.Namespace("Core.Trait"))
            using (generator.Class("public static class TraitIDs"))
            {
                foreach (TraitDefinition definition in TraitDatabase.GetDefinitions())
                {
                    TraitID id = definition.ID;

                    generator.Field($"public static readonly TraitID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
        private void GenerateGraph()
        {
            StringBuilder sb = new();
            sb.AppendLine("digraph Traits");
            sb.AppendLine("{");
            {
                foreach (TraitDefinition definition in TraitDatabase.GetDefinitions())
                {
                    bool hasIncompatibles = definition.IncompatibleIDs.Length > 0;

                    if (hasIncompatibles)
                    {
                        foreach (TraitID incompatibleID in definition.IncompatibleIDs)
                        {
                            if (incompatibleID.IsValid)
                            {
                                sb.AppendLine($"  \"{definition.ID.Key}\" -> \"{incompatibleID.Key}\";");
                            }
                        }
                    }
                    else
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\";");
                    }
                }
            }
            sb.AppendLine("}");

            Editor.EditorUtility.GenerateTextFile(graphPath, sb.ToString());
        }
#endif
    }
}
