using System.Collections.Generic;
using UnityEngine;
using Core.Editor;

namespace Core.Prefab
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_PrefabRegistry", menuName = "Resources/Core/Prefab Registry", order = 0)]
    public sealed class RegistryPrefab : Registry
    {
        [Header("_")]
        [SerializeField, Required] private List<GameObject> entries = null;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedPrefabIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => PrefabDatabase.Build(entries);

#if UNITY_EDITOR
        [Clickable("Build")]
        internal void Build()
        {
            BuildDatabase();
            Generate();
        }

        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Prefab");
            generator.Line();

            using (generator.Namespace("Core.Prefab"))
            using (generator.Class("public static class PrefabIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in PrefabDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;

                    generator.Field($"public static readonly PrefabID {id.ToIdentifier()} = new({id.ToLiteral()})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        public void Register(GameObject obj) => entries.Add(obj);
        public void Unregister(GameObject obj) => entries.Remove(obj);
#endif
    }
}
