using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Core.Prefab
{
    [CreateAssetMenu(fileName = "SCO_PrefabRegistry", menuName = "Resources/Core/Prefab Registry", order = 0)]
    public sealed class RegistryPrefab : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private List<GameObject> entries = null;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedPrefabIDs.cs";

        private readonly Dictionary<string, GameObject> extraEntries = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => PrefabDatabase.Build(CoreUtility.MergeEntries(entries.ToArray(), extraEntries, static entry => entry != null ? entry.name : CoreUtility.STRING_NULL));
        public void AppendEntries(IReadOnlyList<GameObject> prefabs) => CoreUtility.AppendEntries(prefabs, extraEntries, static entry => entry.name, static entry => entry != null);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Prefab");
            generator.Line();

            using (generator.Namespace("Core.Prefab"))
            using (generator.Class("public static class PrefabIDs"))
            {
                for (int i = 0; i < PrefabDatabase.GetPrefabs(); i++)
                {
                    PrefabID id = PrefabDatabase.GetID(i);
    
                    generator.Field($"public static readonly PrefabID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }

        public void Register(GameObject obj)
        {
            entries.Add(obj);

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
        public void Unregister(GameObject obj)
        {
            entries.Remove(obj);

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
