using UnityEngine;
using Core.Editor;

namespace Core.Effect
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_EffectRegistry", menuName = "Resources/Core/Effect Registry", order = 10)]
    public sealed class RegistryEffect : Registry
    {
        [Header("_")]
        [SerializeField] private EffectEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedEffectIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => EffectDatabase.Build(entries);

#if UNITY_EDITOR
        [Clickable("Build")]
        public void Build()
        {
            BuildDatabase();
            Generate();
        }

        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Effect");
            generator.Line();

            using (generator.Namespace("Core.Effect"))
            using (generator.Class("public static class EffectIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in EffectDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = EffectDatabase.GetIndex(id);

                    generator.Field($"public static readonly EffectID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        /// <summary> Overrides entries </summary>
        public void Override(EffectEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new EffectEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = new(entries[i]);
            }
        }
#endif
    }
}
