using System.Collections.Generic;
using UnityEngine;

namespace Core.Effect
{
    [CreateAssetMenu(fileName = "SCO_EffectRegistry", menuName = "Resources/Core/Effect Registry", order = 10)]
    public sealed class RegistryEffect : Registry
    {
        [Header("_")]
        [SerializeField] private EffectEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedEffectIDs.cs";

        private readonly Dictionary<string, EffectEntry> extraEntries = new();

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => EffectDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key));
        public void AppendEntries(IReadOnlyList<EffectEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Effect"))
            using (generator.Class("public static class EffectIDs"))
            {
                foreach (EffectDefinition definition in EffectDatabase.GetDefinitions())
                {
                    string id = definition.ID.Key;
                    int index = definition.ID.Index;

                    generator.Field($"public static readonly EffectID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
