using Core.Editor;
using UnityEditor;
using UnityEngine;

namespace Core.Effect
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_EffectRegistry", menuName = "Resources/Core/Effect Registry", order = 10)]
    public sealed class RegistryEffect : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;

        [Header("_")]
        [SerializeField] private EffectEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedEffectIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => EffectDatabase.Build(ids, entries);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Effect");
            generator.Line();

            using (generator.Namespace("Core.Effect"))
            using (generator.Class("public static class EffectIDs"))
            {
                foreach (SearchEntry<string> entry in EffectDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = EffectDatabase.GetIDIndex(id);

                    generator.Field($"public static readonly EffectID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides entries </summary>
        public void OverrideEntries(EffectEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new EffectEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
