using System;
using System.Collections.Generic;
using UnityEngine;

namespace Core.Weapon
{
    [CreateAssetMenu(fileName = "SCO_WeaponRegistry", menuName = "Resources/Core/Weapon Registry", order = 10)]
    public sealed class RegistryWeapon : Registry
    {
        public override int Priority => 5;

        [Header("_")]
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField] private WeaponEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedWeaponIDs.cs";
        [SerializeField, Required] private string tagsPath = "Assets/Scripts/SCR_GeneratedWeaponTags.cs";

        private readonly Dictionary<string, WeaponEntry> extraEntries = new();
        private readonly HashSet<string> extraTags = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => WeaponDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key), CoreUtility.MergeEntries(tags, extraTags));
        public void AppendEntries(IReadOnlyList<WeaponEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);
        public void AppendTags(IReadOnlyList<string> tags) => CoreUtility.AppendUnique(tags, extraTags, StringComparer.Ordinal);

#if UNITY_EDITOR
        protected override void OnValidate()
        {
            base.OnValidate();

            for (int i = 0; i < entries.Length; i++)
            {
                entries[i].OnValidate();
            }

            Editor.ReferenceUtility.FixReferences(this);
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
            GenerateIDs();
        }

        private void GenerateTags()
        {
            Core.Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Weapon"))
            using (generator.Class("public static class WeaponTags"))
            {
                foreach (WeaponTag tag in WeaponDatabase.GetTags())
                {
                    generator.Field($"public static readonly WeaponTag {tag.Key.ToIdentifier()} = new({tag.Key.ToLiteral()},{tag.Index})");
                }
            }

            Core.Editor.EditorUtility.GenerateTextFile(tagsPath, generator.ToString());
        }
        private void GenerateIDs()
        {
            Core.Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Weapon"))
            using (generator.Class("public static class WeaponIDs"))
            {
                foreach (WeaponDefinition definition in WeaponDatabase.GetDefinitions())
                {
                    WeaponID id = definition.ID;

                    generator.Field($"public static readonly WeaponID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Core.Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
