using UnityEngine;
using Core.Editor;

namespace Core.Surface
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_SurfaceRegistry", menuName = "Resources/Core/Surface Registry", order = 10)]
    public sealed class RegistrySurface : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedSurfaceTags.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => SurfaceDatabase.Build(entries);

#if UNITY_EDITOR
        [Clickable("Build")]
        internal void Build()
        {
            BuildDatabase();
            Generate();
        }

        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Surface");
            generator.Line();

            using (generator.Namespace("Core.Surface"))
            using (generator.Class("public static class SurfaceTags"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in SurfaceDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = SurfaceDatabase.GetIndex(id);

                    generator.Field($"public static readonly SurfaceTag {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        public void Override(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }
        }
#endif
    }
}
