using System;
using System.Collections.Generic;
using UnityEngine;

namespace Core.Surface
{
    [CreateAssetMenu(fileName = "SCO_SurfaceRegistry", menuName = "Resources/Core/Surface Registry", order = 10)]
    public sealed class RegistrySurface : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField, Required] private string tagPath = "Assets/Scripts/SCR_GeneratedSurfaceTags.cs";

        private readonly HashSet<string> extraTags = new();

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => SurfaceDatabase.Build(CoreUtility.MergeEntries(tags, extraTags));
        public void AppendTags(IReadOnlyList<string> tags) => CoreUtility.AppendUnique(tags, extraTags, StringComparer.Ordinal);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
        }

        private void GenerateTags()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Surface");
            generator.Line();

            using (generator.Namespace("Core.Surface"))
            using (generator.Class("public static class SurfaceTags"))
            {
                foreach (SurfaceTag tag in SurfaceDatabase.GetTags())
                {
                    string key = tag.Key;
                    int index = tag.Index;

                    generator.Field($"public static readonly SurfaceTag {key.ToIdentifier()} = new({key.ToLiteral()},{index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(tagPath, generator.ToString());
        }
#endif
    }
}
