using Core.Editor;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Core.Quest
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_QuestRegistry", menuName = "Resources/Core/Quest Registry", order = 10)]
    public sealed class RegistryQuest : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;

        [Header("_")]
        [SerializeField] private QuestEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string idsPath = "Assets/Scripts/SCR_GeneratedQuestIDs.cs";
        [SerializeField, Info("You can use 'dreampuf.github.io' for graph view"), Required] private string graphPath = "Assets/Data/SCO_GeneratedQuestGraph.dot";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => QuestDatabase.Build(ids, entries);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
            GenerateGraph();
        }

        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Quest");
            generator.Line();

            using (generator.Namespace("Core.Quest"))
            using (generator.Class("public static class QuestIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in QuestDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;

                    generator.Field($"public static readonly QuestID {id.ToIdentifier()} = new({id.ToLiteral()})");
                }
            }

            GenerateTextFile(idsPath, generator.ToString());
        }
        private void GenerateGraph()
        {
            StringBuilder sb = new();
            sb.AppendLine("digraph Quests");
            sb.AppendLine("{");
            {
                foreach (QuestDefinition definition in QuestDatabase.GetDatabase()) // senin veri kaynaðýn neyse
                {
                    if (definition.NextID.IsValid)
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\" -> \"{definition.NextID.Key}\";");
                    }
                    else
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\";");
                    }
                }
            }
            sb.AppendLine("}");

            GenerateTextFile(graphPath, sb.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides entries </summary>
        public void OverrideEntries(QuestEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new QuestEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
