using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace Core.Quest
{
    [CreateAssetMenu(fileName = "SCO_QuestRegistry", menuName = "Resources/Core/Quest Registry", order = 10)]
    public sealed class RegistryQuest : Registry
    {
        [Header("_")]
        [SerializeField] private QuestEntry[] entries;

        [Header("_")]
        [Info("You can use 'dreampuf.github.io' for graph view")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedQuestIDs.cs";
        [SerializeField, Required] private string graphPath = "Assets/Data/SCO_GeneratedQuestGraph.dot";

        private readonly Dictionary<string, QuestEntry> extraEntries = new();

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => QuestDatabase.Build(CoreUtility.MergeEntries(entries, extraEntries, static entry => entry.ID.Key));
        public void AppendEntries(IReadOnlyList<QuestEntry> entries) => CoreUtility.AppendEntries(entries, extraEntries, static entry => entry.ID.Key, static entry => entry.ID.IsValid);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
            GenerateGraph();
        }

        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Quest");
            generator.Line();

            using (generator.Namespace("Core.Quest"))
            using (generator.Class("public static class QuestIDs"))
            {
                foreach (QuestDefinition definition in QuestDatabase.GetDefinitions())
                {
                    QuestID id = definition.ID;

                    generator.Field($"public static readonly QuestID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
        private void GenerateGraph()
        {
            StringBuilder sb = new();
            sb.AppendLine("digraph Quests");
            sb.AppendLine("{");
            {
                foreach (QuestDefinition definition in QuestDatabase.GetDefinitions())
                {
                    if (definition.NextID.IsValid)
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\" -> \"{definition.NextID.Key}\";");
                    }
                    else
                    {
                        sb.AppendLine($"  \"{definition.ID.Key}\";");
                    }
                }
            }
            sb.AppendLine("}");

            Editor.EditorUtility.GenerateTextFile(graphPath, sb.ToString());
        }
#endif
    }
}
