using UnityEngine;

namespace Core.Event
{
    [CreateAssetMenu(fileName = "SCO_EventRegistry", menuName = "Resources/Core/Event Registry", order = 10)]
    public sealed class RegistryEvent : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private string[] ids;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedEventIDs.cs";

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => EventDatabase.Build(ids);


#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateIDs();
        }
        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Event"))
            using (generator.Class("public static class EventIDs"))
            {
                foreach (EventID id in EventDatabase.GetIDs())
                {
                    generator.Field($"public static readonly EventID {id.Key.ToIdentifier()} = new({id.Key.ToLiteral()},{id.Index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
