using System;
using System.Collections.Generic;
using UnityEngine;

namespace Core.Actors
{
    [CreateAssetMenu(fileName = "SCO_ActorRegistry", menuName = "Resources/Core/Actor Registry", order = 10)]
    public sealed class RegistryActor : Registry
    {
        public override int Priority => -10;

        [Header("_")]
        [SerializeField, Required] private string[] ids;
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField, Required] private string idPath = "Assets/Scripts/SCR_GeneratedActorIDs.cs";
        [SerializeField, Required] private string tagPath = "Assets/Scripts/SCR_GeneratedActorTags.cs";

        private readonly HashSet<string> extraIDs = new();
        private readonly HashSet<string> extraTags = new();

        public override void OnAfterAssembliesLoaded() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => ActorDatabase.Build(CoreUtility.MergeEntries(ids, extraIDs), CoreUtility.MergeEntries(tags, extraTags));
        public void AppendIDs(IReadOnlyList<string> ids) => CoreUtility.AppendUnique(ids, extraIDs, StringComparer.Ordinal);
        public void AppendTags(IReadOnlyList<string> tags) => CoreUtility.AppendUnique(tags, extraTags, StringComparer.Ordinal);

#if UNITY_EDITOR
        public override void Reload()
        {
            BuildDatabase();
            GenerateTags();
            GenerateIDs();
        }

        private void GenerateTags()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Actors"))
            using (generator.Class("public static class ActorTags"))
            {
                foreach (ActorTag entry in ActorDatabase.GetTags())
                {
                    string id = entry.Key;
                    int index = entry.Index;

                    generator.Field($"public static readonly ActorTag {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(tagPath, generator.ToString());
        }
        private void GenerateIDs()
        {
            Editor.SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Line();

            using (generator.Namespace("Core.Actors"))
            using (generator.Class("public static class ActorIDs"))
            {
                foreach (ActorGroup entry in ActorDatabase.GetGroups())
                {
                    string id = entry.ID.Key;
                    int index = entry.ID.Index;

                    generator.Field($"public static readonly ActorID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            Editor.EditorUtility.GenerateTextFile(idPath, generator.ToString());
        }
#endif
    }
}
