using UnityEngine;
using Core.Editor;

namespace Core.Actors
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_ActorRegistry", menuName = "Resources/Core/Actor Registry", order = 10)]
    public sealed class RegistryActor : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;
        [SerializeField, Required] private string[] tags;

        [Header("_")]
        [SerializeField, Required] private string idsPath = "Assets/Scripts/SCR_GeneratedActorIDs.cs";
        [SerializeField, Required] private string tagPath = "Assets/Scripts/SCR_GeneratedActorTags.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => ActorDatabase.Build(ids, tags);

#if UNITY_EDITOR
        [Clickable("Build")]
        internal void Build()
        {
            BuildDatabase();
            GenerateTags();
            GenerateIDs();
        }

        private void GenerateTags()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Actors");
            generator.Line();

            using (generator.Namespace("Core.Actors"))
            using (generator.Class("public static class ActorTags"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in ActorDatabase.GetTags().Entries)
                {
                    string id = entry.Value;
                    int index = ActorDatabase.GetTagIndex(id);

                    generator.Field($"public static readonly ActorTag {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(tagPath, generator.ToString());
        }
        private void GenerateIDs()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Actors");
            generator.Line();

            using (generator.Namespace("Core.Actors"))
            using (generator.Class("public static class ActorIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in ActorDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = ActorDatabase.GetIDIndex(id);

                    generator.Field($"public static readonly ActorID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(idsPath, generator.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }
        }

        /// <summary> Overrides tags </summary>
        public void OverrideTags(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            tags = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                tags[i] = entries[i];
            }
        }
#endif
    }
}
