using Core.Editor;
using UnityEditor;
using UnityEngine;

namespace Core.Stat
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_StatRegistry", menuName = "Resources/Core/Stat Registry", order = 10)]
    public sealed class RegistryStat : Registry
    {
        [Header("_")]
        [SerializeField, Required] private string[] ids;

        [Header("_")]
        [SerializeField] private StatEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedStatIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => StatDatabase.Build(ids, entries);

#if UNITY_EDITOR
        private void OnValidate()
        {
            for (int i = 0; i < entries.Length; i++) entries[i].Name = entries[i].ID.Key;
        }

        public override void Reload()
        {
            BuildDatabase();
            Generate();
        }

        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Stat");
            generator.Line();

            using (generator.Namespace("Core.Stat"))
            using (generator.Class("public static class StatIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in StatDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;

                    generator.Field($"public static readonly StatID {id.ToIdentifier()} = new({id.ToLiteral()})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        /// <summary> Overrides ids </summary>
        public void OverrideIDs(string[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            ids = new string[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                ids[i] = entries[i];
            }

            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        /// <summary> Overrides entries </summary>
        public void Override(StatEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new StatEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = entries[i];
            }


            UnityEditor.EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }
#endif
    }
}
