using UnityEngine;
using Core.Editor;

namespace Core.Stat
{
    using static CoreUtility;

    [CreateAssetMenu(fileName = "SCO_StatRegistry", menuName = "Resources/Core/Stat Registry", order = 10)]
    public sealed class RegistryStat : Registry
    {
        [Header("_")]
        [SerializeField] private StatEntry[] entries;

        [Header("_")]
        [SerializeField, Required] private string path = "Assets/Scripts/SCR_GeneratedStatIDs.cs";

        public override void OnBeforeSceneLoad() => BuildDatabase();
        public override void OnAfterScriptLoad() => BuildDatabase();
        public void BuildDatabase() => StatDatabase.Build(entries);

#if UNITY_EDITOR
        [Clickable("Build")]
        internal void Build()
        {
            BuildDatabase();
            Generate();
        }

        private void Generate()
        {
            SourceGenerator generator = new();

            generator.AutoGenerated();

            generator.Using("System");
            generator.Using("Core.Stat");
            generator.Line();

            using (generator.Namespace("Core.Stat"))
            using (generator.Class("public static class StatIDs"))
            {
                generator.Line();

                foreach (SearchEntry<string> entry in StatDatabase.GetIDs().Entries)
                {
                    string id = entry.Value;
                    int index = StatDatabase.GetIndex(id);

                    generator.Field($"public static readonly StatID {id.ToIdentifier()} = new({id.ToLiteral()},{index})");
                }
            }

            GenerateTextFile(path, generator.ToString());
        }

        /// <summary> Overrides entries </summary>
        public void Override(StatEntry[] entries)
        {
            if (entries == null)
            {
                Debug.LogError("Registry override entry cannot be null!");
                return;
            }

            this.entries = new StatEntry[entries.Length];

            for (int i = 0; i < entries.Length; i++)
            {
                this.entries[i] = new(entries[i]);
            }
        }
#endif
    }
}
